name: Create and Update Releases

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  get-release:
    runs-on: ubuntu-latest
    outputs: 
      latest_release: ${{ steps.get_latest_release.outputs.latest_release }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the latest release tag
        id: get_latest_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          latest_release=$(gh release list --limit 1 --json tagName --jq '.[0].tagName' || echo "none")
          echo "Latest release tag: $latest_release"
          echo "latest_release=${latest_release}" >> $GITHUB_ENV
        continue-on-error: true

  create-release:
    needs: get-release
    runs-on: ubuntu-latest
    if: needs.get-release.outputs.latest_release == ''
    steps:
      - name: print latest release output
        run: echo "Latest release ${{ needs.get-release.outputs.latest_release }}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Release doesn't exist so create one
        id: create_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v1.0.0 --generate-notes --prerelease=false
          echo "Release created"
      
      - name: Zip files of folders
        id: zip_folders
        run: |
          mkdir -p temp
          for folder in */; do
            if [ -d "$folder" ]; then
              folder_name=$(basename)
              zip -r "temp/${folder_name}.zip" "$folder_name"
            fi
          done
          echo "Zip files created"
    
      - name: upload files to the release
        run: |
          for file in temp/*.zip; do
            gh release upload v1.0.0 "$file" --clobber
            echo "Uploaded $file, waiting to avoid rate limits..."
            sleep 3  
          done
    
      - name: clean up
        run: |
          rm -r temp

  update-release:
    needs: get-release
    if: needs.get-release.outputs.latest_release != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch the latest release tag from remote
        if: env.latest_release != ''
        run: |
          git fetch origin refs/tags/${{ env.latest_release }}:refs/tags/${{ env.latest_release }}

      - name: Get changed files since latest releases
        id: get_changes
        run: |
          if [ -n "${{ env.latest_release }}" ]; then
            git fetch origin refs/tags/${{ env.latest_release }}:refs/tags/${{ env.latest_release }}
            changed_files=$(git diff --name-only ${{ env.latest_release }} HEAD)
            echo "Changed files since ${{ env.latest_release }}: $changed_files"
            echo "$changed_files" > changed_files.txt
          else
            echo "No latest release found"
            echo "" > changed_files.txt
          fi

      - name: Identify changed folders
        id: identify_folders
        run: |
          if [ -s changed_files.txt ]; then
            changed_folders=$(awk -F/ '{print $1}' changed_files.txt | sort | uniq)
            echo "Changed folders: $changed_folders"
            echo "$changed_folders" > changed_folders.txt
          else
            echo "No changed files to process"
            echo "" > changed_folders.txt
          fi

      - name: Archive changed folders
        run: |
          while IFS= read -r folder; do
            if [ -d "$folder" ]; then
              tar -cvf "$folder.tar" "$folder"
              echo "Created archive for $folder"
            else
              echo "Folder $folder not found"
            fi
          done < changed_folders.txt

      - name: Upload changed archives to the release
        if: env.latest_release != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          while IFS= read -r folder; do
            archive="$folder.tar"
            if [ -f "$archive" ]; then
              echo "Uploading $archive to release ${{ env.latest_release }}"
              gh release upload ${{ env.latest_release }} "$archive" --clobber
            else
              echo "Archive $archive not found"
            fi
          done < changed_folders.txt
